const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');const overlay=document.querySelector('#overlay'),title=document.querySelector('#ovTitle'),text=document.querySelector('#ovText'),levelEl=document.querySelector('#level'),statusEl=document.querySelector('#status');
let level=+(localStorage.getItem('mazeBallLevel')||1),N=9,maze=[],ball={},goal={},running=false,keyboard=false,last=0,ax=0,ay=0,keys={};
function generate(n){N=n;maze=Array.from({length:n},()=>Array.from({length:n},()=>({v:false,w:[1,1,1,1]})));let stack=[[0,0]];maze[0][0].v=true;while(stack.length){let [x,y]=stack.at(-1),opts=[];[[0,-1,0,2],[1,0,1,3],[0,1,2,0],[-1,0,3,1]].forEach(([dx,dy,a,b])=>{let nx=x+dx,ny=y+dy;if(nx>=0&&(ny>=0)&&nx<n&&ny<n&&!maze[ny][nx].v)opts.push([nx,ny,a,b])});if(!opts.length){stack.pop();continue}let [nx,ny,a,b]=opts[Math.random()*opts.length|0];maze[y][x].w[a]=0;maze[ny][nx].w[b]=0;maze[ny][nx].v=true;stack.push([nx,ny])}maze.forEach(r=>r.forEach(c=>delete c.v));ball={x:.5,y:.5,vx:0,vy:0,r:.22};goal={x:N-.5,y:N-.5};}
function resize(){let d=devicePixelRatio||1,s=canvas.clientWidth;canvas.width=s*d;canvas.height=s*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function draw(){let S=canvas.clientWidth,c=S/N;ctx.clearRect(0,0,S,S);ctx.fillStyle='#f7f9fc';ctx.fillRect(0,0,S,S);ctx.fillStyle='#baf7d1';ctx.fillRect((N-1)*c,(N-1)*c,c,c);ctx.strokeStyle='#111827';ctx.lineWidth=Math.max(3,c*.075);ctx.lineCap='round';for(let y=0;y<N;y++)for(let x=0;x<N;x++){let w=maze[y][x].w,X=x*c,Y=y*c;ctx.beginPath();if(w[0]){ctx.moveTo(X,Y);ctx.lineTo(X+c,Y)}if(w[1]){ctx.moveTo(X+c,Y);ctx.lineTo(X+c,Y+c)}if(w[2]){ctx.moveTo(X,Y+c);ctx.lineTo(X+c,Y+c)}if(w[3]){ctx.moveTo(X,Y);ctx.lineTo(X,Y+c)}ctx.stroke()}let gx=goal.x*c,gy=goal.y*c;ctx.beginPath();ctx.arc(gx,gy,c*.18,0,Math.PI*2);ctx.fillStyle='#21c875';ctx.fill();let x=ball.x*c,y=ball.y*c,r=ball.r*c,g=ctx.createRadialGradient(x-r*.35,y-r*.45,r*.05,x,y,r);g.addColorStop(0,'#d9f4ff');g.addColorStop(.25,'#4fb7ff');g.addColorStop(1,'#0752b8');ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=g;ctx.shadowColor='#0059cc88';ctx.shadowBlur=10;ctx.fill();ctx.shadowBlur=0}
function collide(){let r=ball.r,x=ball.x,y=ball.y,cx=Math.floor(x),cy=Math.floor(y);cx=Math.max(0,Math.min(N-1,cx));cy=Math.max(0,Math.min(N-1,cy));let w=maze[cy][cx].w,b=.22;if(w[3]&&x-r<cx){ball.x=cx+r;ball.vx=Math.abs(ball.vx)*b}if(w[1]&&x+r>cx+1){ball.x=cx+1-r;ball.vx=-Math.abs(ball.vx)*b}if(w[0]&&y-r<cy){ball.y=cy+r;ball.vy=Math.abs(ball.vy)*b}if(w[2]&&y+r>cy+1){ball.y=cy+1-r;ball.vy=-Math.abs(ball.vy)*b}}
function tick(t){if(!running){draw();requestAnimationFrame(tick);return}let dt=Math.min(.025,(t-last)/1000||.016);last=t;if(keyboard){ax=((keys.ArrowRight||keys.d)?1:0)-((keys.ArrowLeft||keys.a)?1:0);ay=((keys.ArrowDown||keys.s)?1:0)-((keys.ArrowUp||keys.w)?1:0)}let force=7.5;ball.vx+=ax*force*dt;ball.vy+=ay*force*dt;let sp=Math.hypot(ball.vx,ball.vy),max=4.2;if(sp>max){ball.vx*=max/sp;ball.vy*=max/sp}ball.vx*=Math.pow(.985,dt*60);ball.vy*=Math.pow(.985,dt*60);let steps=4;for(let i=0;i<steps;i++){ball.x+=ball.vx*dt/steps;collide();ball.y+=ball.vy*dt/steps;collide()}if(Math.hypot(ball.x-goal.x,ball.y-goal.y)<.35)win();draw();requestAnimationFrame(tick)}
function newLevel(){levelEl.textContent=level;generate(Math.min(18,8+level));resize();statusEl.textContent=keyboard?'⌨️ Flèches / WASD':'📱 Incline le téléphone';}
function win(){if(!running)return;running=false;navigator.vibrate?.([60,40,100]);level++;localStorage.setItem('mazeBallLevel',level);title.textContent='Bravo ! 🎉';text.textContent='La bille a atteint la sortie. Le prochain labyrinthe sera plus difficile.';document.querySelector('#start').textContent='Niveau suivant';overlay.classList.remove('hidden');}
async function startMotion(){keyboard=false;try{if(typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'){let p=await DeviceMotionEvent.requestPermission();if(p!=='granted')throw Error()}window.addEventListener('deviceorientation',e=>{let o=screen.orientation?.angle??window.orientation??0,b=(e.beta||0)/25,g=(e.gamma||0)/25;if(o===90){ax=b;ay=-g}else if(o===-90||o===270){ax=-b;ay=g}else if(o===180){ax=-g;ay=-b}else{ax=-g;ay=-b}ax=Math.max(-1,Math.min(1,ax));ay=Math.max(-1,Math.min(1,ay))});begin()}catch{keyboard=true;statusEl.textContent='Capteurs indisponibles — mode clavier';begin()}}
function begin(){if(!maze.length||!running)newLevel();overlay.classList.add('hidden');running=true;last=performance.now()}
document.querySelector('#start').onclick=startMotion;document.querySelector('#keyboard').onclick=()=>{keyboard=true;begin()};document.querySelector('#reset').onclick=()=>{running=false;newLevel();running=true;last=performance.now()};addEventListener('keydown',e=>{keys[e.key]=true});addEventListener('keyup',e=>{keys[e.key]=false});addEventListener('resize',resize);newLevel();requestAnimationFrame(tick);
